"""FastAPI backend for StyleAI virtual outfit generation."""
from __future__ import annotations

import httpx
from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from config import settings
from models import OutfitResponse
from services.ai import generate_local_preview, generate_with_replicate, get_affiliate_link
from services.storage import event_record, history_store, save_upload

app = FastAPI(title=settings.app_name)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins_list,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

settings.uploads_dir.mkdir(parents=True, exist_ok=True)
settings.generated_dir.mkdir(parents=True, exist_ok=True)

app.mount("/uploads", StaticFiles(directory=settings.uploads_dir), name="uploads")
app.mount("/generated", StaticFiles(directory=settings.generated_dir), name="generated")


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok", "env": settings.app_env}


@app.post("/generate-outfit", response_model=OutfitResponse)
async def generate_outfit(
    image: UploadFile = File(...),
    style: str = Form(...),
) -> OutfitResponse:
    if image.content_type not in {"image/jpeg", "image/png", "image/webp"}:
        raise HTTPException(status_code=400, detail="Only JPG, PNG, and WEBP images are supported.")

    image_bytes = await image.read()
    upload_suffix = ".png" if image.content_type == "image/png" else ".jpg"
    upload_path = save_upload(image_bytes, settings.uploads_dir, suffix=upload_suffix)
    upload_url = f"{settings.base_url}/uploads/{upload_path.name}"

    generated_url = generate_with_replicate(image_bytes, style)
    message = "Generated by Replicate model."

    if not generated_url:
        preview_path = generate_local_preview(image_bytes, style, settings.generated_dir)
        generated_url = f"{settings.base_url}/generated/{preview_path.name}"
        message = "Replicate token/model not configured or unavailable; returned local preview fallback."

    # Cache remote image locally so frontend can serve stable URL.
    if generated_url.startswith("http") and "generated/" not in generated_url:
        try:
            async with httpx.AsyncClient(timeout=45) as client:
                response = await client.get(generated_url)
                response.raise_for_status()
            local_path = save_upload(response.content, settings.generated_dir, suffix=".jpg")
            generated_url = f"{settings.base_url}/generated/{local_path.name}"
        except Exception:
            # Keep original URL if downloading fails.
            pass

    affiliate_url = get_affiliate_link(style)

    await history_store.save_event(event_record(style=style, upload_url=upload_url, generated_url=generated_url))

    return OutfitResponse(
        generated_image_url=generated_url,
        style=style,
        affiliate_url=affiliate_url,
        message=message,
    )
